import type {
  Application,
  Campaign,
  Influencer,
  PlatformUser,
  TopPost,
} from "./types";

const postCovers = [
  "heat-gradient-soft",
  "heat-gradient-blue",
  "heat-gradient",
];

function genPosts(seed: number, baseReach: number): TopPost[] {
  const captions = [
    "Probando el nuevo producto 🔥",
    "Mi rutina de la mañana ☀️",
    "Respondiendo sus preguntas 💬",
    "Detrás de cámaras del shooting 🎬",
    "Lo que nadie te cuenta… 👀",
    "Colaboración que amé 💜",
  ];
  return Array.from({ length: 6 }).map((_, i) => {
    const r = baseReach * (1 - i * 0.12);
    return {
      caption: captions[i],
      cover: postCovers[(seed + i) % postCovers.length],
      likes: Math.round(r * 0.08),
      comments: Math.round(r * 0.004),
      shares: Math.round(r * 0.02),
      saves: Math.round(r * 0.006),
      reach: Math.round(r),
      views: Math.round(r * 1.6),
      engagement: Math.round((6 + ((seed + i) % 10)) * 10) / 10,
    };
  });
}

export const influencers: Influencer[] = [
  {
    id: "inf-1",
    name: "Thamy Palma Jara",
    handle: "@thamypalma",
    avatar: "",
    niche: ["Salud Mental y Crecimiento Personal", "Lifestyle"],
    platforms: ["instagram", "tiktok"],
    followers: 5100000,
    engagement: 4.8,
    location: "La Florida, RM",
    rating: 5,
    priceFrom: 1200,
    bio: "Creadora de contenido de bienestar y crecimiento personal. Comunidad enorme y muy fiel.",
    verified: true,
    completedCampaigns: 37,
    age: 23,
    region: "Región Metropolitana",
    comuna: "La Florida",
    igFollowers: 1300000,
    ttFollowers: 3800000,
    reviewScore: 5,
    reach: 412000,
    audience: { male: 22, female: 70, other: 8 },
    topPosts: genPosts(1, 480000),
  },
  {
    id: "inf-2",
    name: "Rantes Verdugo",
    handle: "@rantesverdugo",
    avatar: "",
    niche: ["Entretenimiento"],
    platforms: ["instagram", "tiktok"],
    followers: 2300000,
    engagement: 5.6,
    location: "Chile",
    rating: 0,
    priceFrom: 900,
    bio: "Comediante y creador de entretenimiento. Contenido viral en redes.",
    verified: true,
    completedCampaigns: 12,
    age: null,
    region: null,
    comuna: null,
    igFollowers: 1200000,
    ttFollowers: 1100000,
    reviewScore: null,
    reach: 305000,
    audience: { male: 58, female: 34, other: 8 },
    topPosts: genPosts(2, 360000),
  },
  {
    id: "inf-3",
    name: "Paolo Tuninetti",
    handle: "@paolotuninetti",
    avatar: "",
    niche: ["Entretenimiento"],
    platforms: ["instagram", "tiktok"],
    followers: 2780000,
    engagement: 2.43,
    location: "Santiago, RM",
    rating: 4.5,
    priceFrom: 1100,
    bio: "Hola! Soy Paolo Tuninetti, influencer con más de 1M de seguidores en sus redes sociales!",
    verified: true,
    completedCampaigns: 24,
    age: 25,
    region: "Región Metropolitana",
    comuna: "Santiago",
    igFollowers: 979100,
    ttFollowers: 1800000,
    reviewScore: 4.5,
    reach: 366845,
    audience: { male: 61, female: 27, other: 11 },
    topPosts: genPosts(3, 5600000),
  },
  {
    id: "inf-4",
    name: "Natalie Bell",
    handle: "@nataliebell",
    avatar: "",
    niche: ["Entretenimiento", "Lifestyle"],
    platforms: ["instagram", "tiktok"],
    followers: 2950000,
    engagement: 6.1,
    location: "Providencia, RM",
    rating: 0,
    priceFrom: 1000,
    bio: "Lifestyle y entretenimiento. Contenido fresco para audiencias jóvenes.",
    verified: true,
    completedCampaigns: 18,
    age: 27,
    region: "Región Metropolitana",
    comuna: "Providencia",
    igFollowers: 850000,
    ttFollowers: 2100000,
    reviewScore: null,
    reach: 298000,
    audience: { male: 30, female: 62, other: 8 },
    topPosts: genPosts(4, 320000),
  },
  {
    id: "inf-5",
    name: "Canal de Pancho",
    handle: "@canaldepancho",
    avatar: "",
    niche: ["Entretenimiento", "Gaming"],
    platforms: ["instagram", "youtube"],
    followers: 611500,
    engagement: 4.2,
    location: "Coquimbo",
    rating: 0,
    priceFrom: 650,
    bio: "Entretenimiento, retos y gaming. Comunidad activa del norte.",
    verified: false,
    completedCampaigns: 9,
    age: 35,
    region: "Coquimbo",
    comuna: "Coquimbo",
    igFollowers: 611500,
    ttFollowers: null,
    reviewScore: null,
    reach: 88000,
    audience: { male: 64, female: 28, other: 8 },
    topPosts: genPosts(5, 96000),
  },
  {
    id: "inf-6",
    name: "Maca Leichtle",
    handle: "@macaleichtle",
    avatar: "",
    niche: ["Belleza"],
    platforms: ["instagram"],
    followers: 583700,
    engagement: 8.1,
    location: "Providencia, RM",
    rating: 0,
    priceFrom: 700,
    bio: "Skincare y maquillaje. Tutoriales honestos y cercanos.",
    verified: false,
    completedCampaigns: 14,
    age: 33,
    region: "Región Metropolitana",
    comuna: "Providencia",
    igFollowers: 583700,
    ttFollowers: null,
    reviewScore: null,
    reach: 74000,
    audience: { male: 12, female: 82, other: 6 },
    topPosts: genPosts(6, 82000),
  },
  {
    id: "inf-7",
    name: "Nat Vicencio",
    handle: "@natvicencio",
    avatar: "",
    niche: ["Salud Mental y Crecimiento Personal", "Lifestyle"],
    platforms: ["instagram", "tiktok"],
    followers: 486400,
    engagement: 7.4,
    location: "Coquimbo",
    rating: 5,
    priceFrom: 620,
    bio: "Bienestar, hábitos y crecimiento personal. Reviews honestas.",
    verified: true,
    completedCampaigns: 26,
    age: 34,
    region: "Coquimbo",
    comuna: "Coquimbo",
    igFollowers: 465300,
    ttFollowers: 21100,
    reviewScore: 5,
    reach: 64000,
    audience: { male: 18, female: 74, other: 8 },
    topPosts: genPosts(7, 72000),
  },
  {
    id: "inf-8",
    name: "Mariuxi Dominguez",
    handle: "@mariuxidominguez",
    avatar: "",
    niche: ["Viajes y Turismo", "Lifestyle"],
    platforms: ["instagram", "tiktok"],
    followers: 499500,
    engagement: 3.9,
    location: "Colina, RM",
    rating: 5,
    priceFrom: 800,
    bio: "Travel & lifestyle. Experiencias y destinos por todo Chile.",
    verified: true,
    completedCampaigns: 31,
    age: 43,
    region: "Región Metropolitana",
    comuna: "Colina",
    igFollowers: 400300,
    ttFollowers: 99200,
    reviewScore: 5,
    reach: 58000,
    audience: { male: 28, female: 64, other: 8 },
    topPosts: genPosts(8, 66000),
  },
  {
    id: "inf-9",
    name: "María Ignacia Silva",
    handle: "@maigsilva",
    avatar: "",
    niche: ["Cocina y Gastronomía"],
    platforms: ["instagram", "tiktok"],
    followers: 363400,
    engagement: 6.8,
    location: "Santiago, RM",
    rating: 0,
    priceFrom: 540,
    bio: "Recetas fáciles y reseñas gastronómicas.",
    verified: false,
    completedCampaigns: 11,
    age: 33,
    region: "Región Metropolitana",
    comuna: "Santiago",
    igFollowers: 359100,
    ttFollowers: 4300,
    reviewScore: null,
    reach: 48000,
    audience: { male: 24, female: 70, other: 6 },
    topPosts: genPosts(9, 54000),
  },
  {
    id: "inf-10",
    name: "Chantal Gayoso",
    handle: "@chantalgayoso",
    avatar: "",
    niche: ["Fitness y Bienestar"],
    platforms: ["instagram"],
    followers: 347600,
    engagement: 7.9,
    location: "Colina, RM",
    rating: 0,
    priceFrom: 560,
    bio: "Fitness, rutinas y vida sana.",
    verified: false,
    completedCampaigns: 8,
    age: null,
    region: "Región Metropolitana",
    comuna: "Colina",
    igFollowers: 347600,
    ttFollowers: null,
    reviewScore: null,
    reach: 44000,
    audience: { male: 38, female: 56, other: 6 },
    topPosts: genPosts(10, 50000),
  },
  {
    id: "inf-11",
    name: "Valentina Flores",
    handle: "@valeflores",
    avatar: "",
    niche: ["Lifestyle"],
    platforms: ["instagram"],
    followers: 301400,
    engagement: 5.2,
    location: "Chile",
    rating: 5,
    priceFrom: 480,
    bio: "Contenido lifestyle y día a día.",
    verified: true,
    completedCampaigns: 19,
    age: 30,
    region: null,
    comuna: null,
    igFollowers: 301400,
    ttFollowers: 0,
    reviewScore: 5,
    reach: 39000,
    audience: { male: 26, female: 66, other: 8 },
    topPosts: genPosts(11, 44000),
  },
  {
    id: "inf-12",
    name: "Nicole Saravia",
    handle: "@nicolesaravia",
    avatar: "",
    niche: ["Decoración de Interiores y DIY", "Lifestyle"],
    platforms: ["instagram"],
    followers: 300200,
    engagement: 6.0,
    location: "Puente Alto, RM",
    rating: 0,
    priceFrom: 470,
    bio: "Deco, DIY y proyectos para el hogar.",
    verified: false,
    completedCampaigns: 7,
    age: null,
    region: "Región Metropolitana",
    comuna: "Puente Alto",
    igFollowers: 300200,
    ttFollowers: null,
    reviewScore: null,
    reach: 38000,
    audience: { male: 20, female: 74, other: 6 },
    topPosts: genPosts(12, 42000),
  },
  {
    id: "inf-13",
    name: "Rodolfo Sepúlveda",
    handle: "@rodolfosepulveda",
    avatar: "",
    niche: ["Gaming", "Tecnología"],
    platforms: ["instagram", "tiktok", "twitch"],
    followers: 538700,
    engagement: 5.5,
    location: "Cerro Navia, RM",
    rating: 0,
    priceFrom: 720,
    bio: "Gaming, tech y streaming. Comunidad gamer activa.",
    verified: false,
    completedCampaigns: 13,
    age: 27,
    region: "Región Metropolitana",
    comuna: "Cerro Navia",
    igFollowers: 295600,
    ttFollowers: 243100,
    reviewScore: null,
    reach: 61000,
    audience: { male: 72, female: 22, other: 6 },
    topPosts: genPosts(13, 68000),
  },
  {
    id: "inf-14",
    name: "Constanza Hidalgo",
    handle: "@constanzahidalgo",
    avatar: "",
    niche: ["Moda", "Belleza"],
    platforms: ["instagram", "tiktok"],
    followers: 388100,
    engagement: 6.4,
    location: "Colina, RM",
    rating: 0,
    priceFrom: 600,
    bio: "Moda, belleza y tendencias.",
    verified: false,
    completedCampaigns: 16,
    age: 30,
    region: "Región Metropolitana",
    comuna: "Colina",
    igFollowers: 269800,
    ttFollowers: 118300,
    reviewScore: null,
    reach: 52000,
    audience: { male: 16, female: 78, other: 6 },
    topPosts: genPosts(14, 58000),
  },
];

export const campaigns: Campaign[] = [
  {
    id: "cmp-1",
    title: "nuevaisapre.cl",
    brand: "Nueva Isapre",
    brandLogo: "🩺",
    status: "active",
    niche: "Salud",
    collabTypes: ["reel", "post", "story"],
    platforms: ["instagram", "tiktok"],
    budget: 12000,
    payPerCreator: 850,
    spots: 12,
    filled: 4,
    applicants: 34,
    deadline: "2026-05-28",
    createdAt: "2026-05-02",
    cover: "heat-gradient-soft",
    brief:
      "Activación con creadores para dar a conocer nuestra nueva isapre. Buscamos contenido cercano que explique lo simple que es cotizar y cambiarse.",
    deliverables: [
      "1 Reel principal (15-30s)",
      "2 Stories con sticker de enlace",
      "1 Post en feed",
    ],
    requirements: [
      "Audiencia mayoritaria en Chile",
      "Engagement superior al 3%",
      "Tono cercano y confiable",
    ],
    minFollowers: 20000,
    tag: "Orgánico",
  },
  {
    id: "cmp-2",
    title: "Reto fitness 30 días",
    brand: "PowerFuel",
    brandLogo: "💪",
    status: "active",
    niche: "Fitness y Bienestar",
    collabTypes: ["reel", "post"],
    platforms: ["instagram", "youtube"],
    budget: 8000,
    payPerCreator: 600,
    spots: 10,
    filled: 4,
    applicants: 19,
    deadline: "2026-06-30",
    createdAt: "2026-05-10",
    cover: "heat-gradient-blue",
    brief:
      "Campaña para promocionar nuestra línea de suplementos durante un reto de 30 días con creadores fitness.",
    deliverables: [
      "1 vídeo de presentación del reto",
      "3 actualizaciones de progreso",
      "1 vídeo de resultados finales",
    ],
    requirements: [
      "Nicho fitness/wellness",
      "Constancia en publicaciones",
      "Audiencia activa",
    ],
    minFollowers: 15000,
    tag: "Pagado",
  },
  {
    id: "cmp-3",
    title: "Review tech: auriculares Pulse",
    brand: "Nexa Audio",
    brandLogo: "🎧",
    status: "review",
    niche: "Tecnología",
    collabTypes: ["post", "clip"],
    platforms: ["youtube", "tiktok"],
    budget: 15000,
    payPerCreator: 1400,
    spots: 8,
    filled: 8,
    applicants: 41,
    deadline: "2026-06-05",
    createdAt: "2026-04-18",
    cover: "heat-gradient",
    brief:
      "Reviews honestas y detalladas de nuestros nuevos auriculares premium.",
    deliverables: ["1 review en vídeo (5-8 min)", "1 clip corto destacando una feature"],
    requirements: ["Experiencia en reviews de tech", "Producción alta"],
    minFollowers: 50000,
    tag: "Pagado",
  },
  {
    id: "cmp-4",
    title: "Recetas saludables de verano",
    brand: "GreenBite",
    brandLogo: "🥗",
    status: "active",
    niche: "Cocina y Gastronomía",
    collabTypes: ["reel", "ugc"],
    platforms: ["instagram", "tiktok"],
    budget: 5000,
    payPerCreator: 350,
    spots: 14,
    filled: 3,
    applicants: 27,
    deadline: "2026-07-10",
    createdAt: "2026-05-15",
    cover: "heat-gradient-soft",
    brief:
      "Creadores de cocina para desarrollar recetas frescas con nuestros productos ecológicos.",
    deliverables: ["2 Reels de recetas", "Material UGC para nuestros canales"],
    requirements: ["Nicho gastronomía/healthy", "Buen storytelling visual"],
    minFollowers: 10000,
    tag: "Orgánico",
  },
  {
    id: "cmp-5",
    title: "Escapada premium — hotel boutique",
    brand: "Vela Resorts",
    brandLogo: "🏝️",
    status: "draft",
    niche: "Viajes y Turismo",
    collabTypes: ["reel", "story", "post"],
    platforms: ["instagram", "youtube"],
    budget: 22000,
    payPerCreator: 2100,
    spots: 6,
    filled: 0,
    applicants: 0,
    deadline: "2026-08-01",
    createdAt: "2026-05-22",
    cover: "heat-gradient",
    brief:
      "Experiencia de viaje premium a cambio de contenido cinematográfico de alta calidad.",
    deliverables: ["1 Reel cinematográfico", "5 Stories durante la estancia", "1 Post"],
    requirements: ["Producción premium", "Audiencia amplia"],
    minFollowers: 100000,
    tag: "Pagado",
  },
  {
    id: "cmp-6",
    title: "Educación financiera Gen Z",
    brand: "FinUp",
    brandLogo: "📈",
    status: "completed",
    niche: "Negocios y Emprendimiento",
    collabTypes: ["post", "clip"],
    platforms: ["youtube", "instagram"],
    budget: 9000,
    payPerCreator: 980,
    spots: 9,
    filled: 9,
    applicants: 22,
    deadline: "2026-04-30",
    createdAt: "2026-03-01",
    cover: "heat-gradient-blue",
    brief: "Campaña educativa sobre nuestra app de inversión dirigida a público joven.",
    deliverables: ["1 vídeo explicativo", "1 clip destacando la app"],
    requirements: ["Nicho finanzas/educación", "Tono responsable"],
    minFollowers: 30000,
    tag: "Afiliación",
  },
];

export const applications: Application[] = [
  {
    id: "app-1",
    campaignId: "cmp-1",
    influencerId: "inf-1",
    status: "shortlisted",
    appliedAt: "2026-05-12",
    message:
      "Me encanta el proyecto. Tengo ideas para un Reel cercano explicando lo fácil que es cotizar.",
    proposedRate: 1200,
  },
  {
    id: "app-2",
    campaignId: "cmp-1",
    influencerId: "inf-7",
    status: "pending",
    appliedAt: "2026-05-14",
    message: "Mi audiencia de bienestar conecta muy bien con temas de salud.",
    proposedRate: 620,
  },
  {
    id: "app-3",
    campaignId: "cmp-1",
    influencerId: "inf-9",
    status: "pending",
    appliedAt: "2026-05-15",
    message: "Puedo aportar un ángulo cotidiano y familiar.",
    proposedRate: 540,
  },
  {
    id: "app-4",
    campaignId: "cmp-1",
    influencerId: "inf-8",
    status: "accepted",
    appliedAt: "2026-05-08",
    message: "Encantada de colaborar, mi comunidad confía en mis recomendaciones.",
    proposedRate: 800,
  },
  {
    id: "app-5",
    campaignId: "cmp-2",
    influencerId: "inf-10",
    status: "accepted",
    appliedAt: "2026-05-11",
    message: "El reto de 30 días es perfecto para mi contenido fitness. ¡Vamos!",
    proposedRate: 560,
  },
  {
    id: "app-6",
    campaignId: "cmp-3",
    influencerId: "inf-13",
    status: "accepted",
    appliedAt: "2026-04-20",
    message: "Tengo equipo de grabación profesional para la review.",
    proposedRate: 720,
  },
  {
    id: "app-7",
    campaignId: "cmp-2",
    influencerId: "inf-3",
    status: "shortlisted",
    appliedAt: "2026-05-16",
    message: "Combinaría entretenimiento con el reto para hacerlo más viral.",
    proposedRate: 1100,
  },
];

export const users: PlatformUser[] = [
  {
    id: "usr-1",
    name: "Nueva Isapre",
    email: "marketing@nuevaisapre.cl",
    role: "brand",
    joinedAt: "2026-01-14",
    status: "active",
    avatar: "🩺",
  },
  {
    id: "usr-2",
    name: "PowerFuel",
    email: "marketing@powerfuel.io",
    role: "brand",
    joinedAt: "2026-02-02",
    status: "active",
    avatar: "💪",
  },
  {
    id: "usr-3",
    name: "Thamy Palma Jara",
    email: "thamy@creators.cl",
    role: "creator",
    joinedAt: "2026-01-20",
    status: "active",
    avatar: "",
  },
  {
    id: "usr-4",
    name: "Paolo Tuninetti",
    email: "contactopaolotuninetti@gmail.com",
    role: "creator",
    joinedAt: "2026-03-05",
    status: "active",
    avatar: "",
  },
  {
    id: "usr-5",
    name: "Nexa Audio",
    email: "hello@nexaaudio.com",
    role: "brand",
    joinedAt: "2026-02-18",
    status: "pending",
    avatar: "🎧",
  },
  {
    id: "usr-6",
    name: "Maca Leichtle",
    email: "maca@creators.cl",
    role: "creator",
    joinedAt: "2026-04-01",
    status: "active",
    avatar: "",
  },
  {
    id: "usr-7",
    name: "María Ignacia Silva",
    email: "maig@creators.cl",
    role: "creator",
    joinedAt: "2026-04-22",
    status: "suspended",
    avatar: "",
  },
];

export function getInfluencer(id: string) {
  return influencers.find((i) => i.id === id);
}

export function getCampaign(id: string) {
  return campaigns.find((c) => c.id === id);
}

export function applicationsForCampaign(campaignId: string) {
  return applications.filter((a) => a.campaignId === campaignId);
}

export function applicationsForInfluencer(influencerId: string) {
  return applications.filter((a) => a.influencerId === influencerId);
}

export const adminMetrics = {
  totalUsers: 1284,
  brands: 312,
  creators: 8000,
  activeCampaigns: 48,
  gmv: 486000,
  revenue: 72900,
  pendingApprovals: 14,
  monthlyGrowth: 18.4,
};

export const gmvSeries = [18, 22, 19, 28, 34, 31, 42, 38, 49, 55, 61, 73];
