import type {
  Application,
  Campaign,
  Influencer,
  PlatformUser,
} from "./types";

export const influencers: Influencer[] = [
  {
    id: "inf-1",
    name: "Lucía Marín",
    handle: "@luciamarin",
    avatar: "",
    niche: ["Moda", "Lifestyle"],
    platforms: ["instagram", "tiktok"],
    followers: 184000,
    engagement: 5.2,
    location: "Madrid, ES",
    rating: 4.9,
    priceFrom: 850,
    bio: "Creadora de moda y lifestyle. Contenido aspiracional con estética minimalista.",
    verified: true,
    completedCampaigns: 42,
  },
  {
    id: "inf-2",
    name: "Diego Torres",
    handle: "@diegofit",
    avatar: "",
    niche: ["Fitness"],
    platforms: ["instagram", "youtube"],
    followers: 96000,
    engagement: 7.8,
    location: "Barcelona, ES",
    rating: 4.7,
    priceFrom: 600,
    bio: "Entrenador personal. Rutinas, nutrición y motivación diaria.",
    verified: true,
    completedCampaigns: 28,
  },
  {
    id: "inf-3",
    name: "Sara Quintana",
    handle: "@saratech",
    avatar: "",
    niche: ["Tecnología", "Gaming"],
    platforms: ["youtube", "twitch", "tiktok"],
    followers: 312000,
    engagement: 4.1,
    location: "Valencia, ES",
    rating: 4.8,
    priceFrom: 1400,
    bio: "Reviews de gadgets, setups y gaming. Comunidad muy fiel y técnica.",
    verified: true,
    completedCampaigns: 61,
  },
  {
    id: "inf-4",
    name: "Mateo Ríos",
    handle: "@mateococina",
    avatar: "",
    niche: ["Comida", "Lifestyle"],
    platforms: ["instagram", "tiktok"],
    followers: 47000,
    engagement: 9.3,
    location: "Sevilla, ES",
    rating: 4.6,
    priceFrom: 320,
    bio: "Recetas rápidas y reseñas gastronómicas. Microinfluencer de alto engagement.",
    verified: false,
    completedCampaigns: 15,
  },
  {
    id: "inf-5",
    name: "Nora Vidal",
    handle: "@noraviaja",
    avatar: "",
    niche: ["Viajes", "Lifestyle"],
    platforms: ["instagram", "youtube"],
    followers: 521000,
    engagement: 3.4,
    location: "Lisboa, PT",
    rating: 4.9,
    priceFrom: 2100,
    bio: "Travel storyteller. Cinematografía de viajes y experiencias premium.",
    verified: true,
    completedCampaigns: 88,
  },
  {
    id: "inf-6",
    name: "Hugo Belmonte",
    handle: "@hugobeauty",
    avatar: "",
    niche: ["Belleza"],
    platforms: ["tiktok", "instagram"],
    followers: 73000,
    engagement: 8.1,
    location: "Málaga, ES",
    rating: 4.5,
    priceFrom: 450,
    bio: "Skincare y maquillaje para todos. Tutoriales honestos y cercanos.",
    verified: false,
    completedCampaigns: 22,
  },
  {
    id: "inf-7",
    name: "Valentina Cruz",
    handle: "@valecrypto",
    avatar: "",
    niche: ["Finanzas", "Tecnología"],
    platforms: ["youtube", "instagram"],
    followers: 145000,
    engagement: 4.6,
    location: "Ciudad de México, MX",
    rating: 4.7,
    priceFrom: 980,
    bio: "Educación financiera para jóvenes. Inversión, ahorro y fintech.",
    verified: true,
    completedCampaigns: 34,
  },
  {
    id: "inf-8",
    name: "Pablo Iglesias",
    handle: "@pablogamer",
    avatar: "",
    niche: ["Gaming"],
    platforms: ["twitch", "youtube"],
    followers: 268000,
    engagement: 6.2,
    location: "Bilbao, ES",
    rating: 4.8,
    priceFrom: 1100,
    bio: "Streamer de variedad. Clips virales y comunidad muy activa.",
    verified: true,
    completedCampaigns: 53,
  },
];

export const campaigns: Campaign[] = [
  {
    id: "cmp-1",
    title: "Lanzamiento colección primavera",
    brand: "Aurora Studio",
    brandLogo: "🌸",
    status: "active",
    niche: "Moda",
    collabTypes: ["reel", "post", "story"],
    platforms: ["instagram", "tiktok"],
    budget: 12000,
    payPerCreator: 850,
    spots: 12,
    filled: 7,
    applicants: 34,
    deadline: "2026-06-20",
    createdAt: "2026-05-02",
    cover: "heat-gradient-soft",
    brief:
      "Buscamos creadoras de moda para mostrar nuestra nueva colección de primavera con un enfoque fresco y aspiracional. Queremos contenido auténtico que conecte con audiencias jóvenes.",
    deliverables: [
      "1 Reel principal (15-30s)",
      "2 Stories con sticker de producto",
      "1 Post en feed",
    ],
    requirements: [
      "Audiencia mayoritaria en España",
      "Engagement superior al 3%",
      "Estética alineada con la marca",
    ],
    minFollowers: 20000,
  },
  {
    id: "cmp-2",
    title: "Reto fitness 30 días",
    brand: "PowerFuel",
    brandLogo: "💪",
    status: "active",
    niche: "Fitness",
    collabTypes: ["reel", "post"],
    platforms: ["instagram", "youtube"],
    budget: 8000,
    payPerCreator: 600,
    spots: 10,
    filled: 4,
    applicants: 19,
    deadline: "2026-06-30",
    createdAt: "2026-05-10",
    cover: "heat-gradient-blue",
    brief:
      "Campaña para promocionar nuestra línea de suplementos durante un reto de 30 días. Buscamos creadores fitness que documenten su progreso usando el producto.",
    deliverables: [
      "1 vídeo de presentación del reto",
      "3 actualizaciones de progreso",
      "1 vídeo de resultados finales",
    ],
    requirements: [
      "Nicho fitness/wellness",
      "Constancia en publicaciones",
      "Audiencia activa y comprometida",
    ],
    minFollowers: 15000,
  },
  {
    id: "cmp-3",
    title: "Review tech: auriculares Pulse",
    brand: "Nexa Audio",
    brandLogo: "🎧",
    status: "review",
    niche: "Tecnología",
    collabTypes: ["post", "clip"],
    platforms: ["youtube", "tiktok"],
    budget: 15000,
    payPerCreator: 1400,
    spots: 8,
    filled: 8,
    applicants: 41,
    deadline: "2026-06-05",
    createdAt: "2026-04-18",
    cover: "heat-gradient",
    brief:
      "Reviews honestas y detalladas de nuestros nuevos auriculares premium. Queremos transparencia y foco en la calidad de sonido y diseño.",
    deliverables: [
      "1 review en vídeo (5-8 min)",
      "1 clip corto destacando una feature",
    ],
    requirements: [
      "Experiencia en reviews de audio/tech",
      "Calidad de producción alta",
    ],
    minFollowers: 50000,
  },
  {
    id: "cmp-4",
    title: "Recetas saludables de verano",
    brand: "GreenBite",
    brandLogo: "🥗",
    status: "active",
    niche: "Comida",
    collabTypes: ["reel", "ugc"],
    platforms: ["instagram", "tiktok"],
    budget: 5000,
    payPerCreator: 350,
    spots: 14,
    filled: 3,
    applicants: 27,
    deadline: "2026-07-10",
    createdAt: "2026-05-15",
    cover: "heat-gradient-soft",
    brief:
      "Creadores de cocina para desarrollar recetas frescas con nuestros productos ecológicos. Contenido tipo UGC, natural y descriptivo.",
    deliverables: ["2 Reels de recetas", "Material UGC para nuestros canales"],
    requirements: ["Nicho gastronomía/healthy", "Buen storytelling visual"],
    minFollowers: 10000,
  },
  {
    id: "cmp-5",
    title: "Escapada premium — hotel boutique",
    brand: "Vela Resorts",
    brandLogo: "🏝️",
    status: "draft",
    niche: "Viajes",
    collabTypes: ["reel", "story", "post"],
    platforms: ["instagram", "youtube"],
    budget: 22000,
    payPerCreator: 2100,
    spots: 6,
    filled: 0,
    applicants: 0,
    deadline: "2026-08-01",
    createdAt: "2026-05-22",
    cover: "heat-gradient",
    brief:
      "Experiencia de viaje premium a cambio de contenido cinematográfico de alta calidad. Buscamos perfiles travel aspiracionales.",
    deliverables: [
      "1 Reel cinematográfico",
      "5 Stories durante la estancia",
      "1 Post en feed",
    ],
    requirements: ["Producción premium", "Audiencia internacional"],
    minFollowers: 100000,
  },
  {
    id: "cmp-6",
    title: "Educación financiera Gen Z",
    brand: "FinUp",
    brandLogo: "📈",
    status: "completed",
    niche: "Finanzas",
    collabTypes: ["post", "clip"],
    platforms: ["youtube", "instagram"],
    budget: 9000,
    payPerCreator: 980,
    spots: 9,
    filled: 9,
    applicants: 22,
    deadline: "2026-04-30",
    createdAt: "2026-03-01",
    cover: "heat-gradient-blue",
    brief:
      "Campaña educativa sobre nuestra app de inversión dirigida a un público joven. Contenido claro, didáctico y responsable.",
    deliverables: ["1 vídeo explicativo", "1 clip destacando la app"],
    requirements: ["Nicho finanzas/educación", "Tono responsable"],
    minFollowers: 30000,
  },
];

export const applications: Application[] = [
  {
    id: "app-1",
    campaignId: "cmp-1",
    influencerId: "inf-1",
    status: "shortlisted",
    appliedAt: "2026-05-12",
    message:
      "Me encanta vuestra estética. Tengo ideas para un Reel con transiciones que encajarían perfecto con la colección.",
    proposedRate: 850,
  },
  {
    id: "app-2",
    campaignId: "cmp-1",
    influencerId: "inf-6",
    status: "pending",
    appliedAt: "2026-05-14",
    message: "Mi audiencia de belleza/moda responde muy bien a lanzamientos.",
    proposedRate: 500,
  },
  {
    id: "app-3",
    campaignId: "cmp-1",
    influencerId: "inf-4",
    status: "pending",
    appliedAt: "2026-05-15",
    message: "Puedo aportar un ángulo lifestyle diferente y cercano.",
    proposedRate: 380,
  },
  {
    id: "app-4",
    campaignId: "cmp-1",
    influencerId: "inf-5",
    status: "accepted",
    appliedAt: "2026-05-08",
    message: "Encantada de colaborar, mi línea editorial encaja totalmente.",
    proposedRate: 2100,
  },
  {
    id: "app-5",
    campaignId: "cmp-2",
    influencerId: "inf-2",
    status: "accepted",
    appliedAt: "2026-05-11",
    message: "El reto de 30 días es perfecto para mi contenido. ¡Vamos!",
    proposedRate: 600,
  },
  {
    id: "app-6",
    campaignId: "cmp-3",
    influencerId: "inf-3",
    status: "accepted",
    appliedAt: "2026-04-20",
    message: "Tengo equipo de grabación profesional para la review.",
    proposedRate: 1400,
  },
  {
    id: "app-7",
    campaignId: "cmp-2",
    influencerId: "inf-4",
    status: "shortlisted",
    appliedAt: "2026-05-16",
    message: "Combinaría fitness con recetas saludables.",
    proposedRate: 400,
  },
];

export const users: PlatformUser[] = [
  {
    id: "usr-1",
    name: "Aurora Studio",
    email: "team@aurorastudio.com",
    role: "brand",
    joinedAt: "2026-01-14",
    status: "active",
    avatar: "🌸",
  },
  {
    id: "usr-2",
    name: "PowerFuel",
    email: "marketing@powerfuel.io",
    role: "brand",
    joinedAt: "2026-02-02",
    status: "active",
    avatar: "💪",
  },
  {
    id: "usr-3",
    name: "Lucía Marín",
    email: "lucia@luciamarin.com",
    role: "creator",
    joinedAt: "2026-01-20",
    status: "active",
    avatar: "",
  },
  {
    id: "usr-4",
    name: "Diego Torres",
    email: "diego@diegofit.es",
    role: "creator",
    joinedAt: "2026-03-05",
    status: "active",
    avatar: "",
  },
  {
    id: "usr-5",
    name: "Nexa Audio",
    email: "hello@nexaaudio.com",
    role: "brand",
    joinedAt: "2026-02-18",
    status: "pending",
    avatar: "🎧",
  },
  {
    id: "usr-6",
    name: "Hugo Belmonte",
    email: "hugo@hugobeauty.com",
    role: "creator",
    joinedAt: "2026-04-01",
    status: "active",
    avatar: "",
  },
  {
    id: "usr-7",
    name: "Mateo Ríos",
    email: "mateo@mateococina.es",
    role: "creator",
    joinedAt: "2026-04-22",
    status: "suspended",
    avatar: "",
  },
];

export function getInfluencer(id: string) {
  return influencers.find((i) => i.id === id);
}

export function getCampaign(id: string) {
  return campaigns.find((c) => c.id === id);
}

export function applicationsForCampaign(campaignId: string) {
  return applications.filter((a) => a.campaignId === campaignId);
}

export function applicationsForInfluencer(influencerId: string) {
  return applications.filter((a) => a.influencerId === influencerId);
}

export const adminMetrics = {
  totalUsers: 1284,
  brands: 312,
  creators: 972,
  activeCampaigns: 48,
  gmv: 486000,
  revenue: 72900,
  pendingApprovals: 14,
  monthlyGrowth: 18.4,
};

/* Serie de 12 meses para el gráfico del dashboard admin. */
export const gmvSeries = [
  18, 22, 19, 28, 34, 31, 42, 38, 49, 55, 61, 73,
];
